#!/usr/bin/env python
from __future__ import absolute_import
from __future__ import print_function

import sys, opkg

def usage():
     sys.stderr.write("%s opk\n" % (sys.argv[0],))
     sys.exit(-1)

if (len(sys.argv) < 2):
     usage()

print(opkg.Package(sys.argv[1]))

